-- MySQL Script generated by MySQL Workbench
-- Wed Feb  8 13:57:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`category` (
  `id_cat` INT NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`warehouse` (
  `id_warehouse` INT NOT NULL AUTO_INCREMENT,
  `warehouse_adress` VARCHAR(120) NOT NULL,
  `warehouse_owner` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_warehouse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`items` (
  `id_items` INT NOT NULL AUTO_INCREMENT,
  `item_name` VARCHAR(45) NOT NULL,
  `itom_desc` VARCHAR(45) NOT NULL,
  `item_cat` INT NOT NULL,
  `item_warehose` INT NOT NULL,
  `item_amount` INT NOT NULL,
  PRIMARY KEY (`id_items`),
  INDEX `item_cat_idx` (`item_cat` ASC) VISIBLE,
  INDEX `item_warehouse_idx` (`item_warehose` ASC) VISIBLE,
  CONSTRAINT `item_cat`
    FOREIGN KEY (`item_cat`)
    REFERENCES `shop`.`category` (`id_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item_warehouse`
    FOREIGN KEY (`item_warehose`)
    REFERENCES `shop`.`warehouse` (`id_warehouse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
